test build all

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -30,35 +30,33 @@ jobs:
         id: integrations
         run: |
           for component in components/*; do
-            if [[ "${{ steps.changed_files.outputs.all }}" =~ $component ]]; then
-              manifestlink=$(jq --raw-output ".manifest" "${component}")
+            manifestlink=$(jq --raw-output ".manifest" "${component}")
 
-              echo "Process: ${component} -> ${manifestlink}"
-              manifest=$(curl -sSL -f "${manifestlink}" | jq -e --raw-output .)
-              if [[ "$?" != 0 ]]; then
-                echo "Unable to read the manifest file at ${manifestlink}"
-                echo "The URL might be wrong or is not a raw URL."
-                exit 1
-              fi
-
-              echo "${manifest}" | jq -e --raw-output '.requirements[0]'
-              if [[ "$?" != 0 ]]; then
-                echo "The integration in $component, does not seem to have any Python requirements."
-                echo "Adding it to this repository has no use, since there are nothing to build for it."
-                exit 1
-              fi
-              
-              for requirement in $(echo "${manifest}" | jq -e --raw-output '.requirements[]'); do
-                if [[ "$requirement" =~ "=" ]] || [[ "$requirement" =~ "<" ]] || [[ "$requirement" =~ ">" ]]; then
-                  echo -e "\t- $requirement"
-                else
-                  echo "::error::The requirement '$requirement' in '$component' is not pinned to a version or a range"
-                  exit 1
-                fi
-              done
-
-              echo "${manifest}" | jq -e --raw-output '.requirements[]' >> requirements.txt
+            echo "Process: ${component} -> ${manifestlink}"
+            manifest=$(curl -sSL -f "${manifestlink}" | jq -e --raw-output .)
+            if [[ "$?" != 0 ]]; then
+              echo "Unable to read the manifest file at ${manifestlink}"
+              echo "The URL might be wrong or is not a raw URL."
+              exit 1
             fi
+
+            echo "${manifest}" | jq -e --raw-output '.requirements[0]'
+            if [[ "$?" != 0 ]]; then
+              echo "The integration in $component, does not seem to have any Python requirements."
+              echo "Adding it to this repository has no use, since there are nothing to build for it."
+              exit 1
+            fi
+            
+            for requirement in $(echo "${manifest}" | jq -e --raw-output '.requirements[]'); do
+              if [[ "$requirement" =~ "=" ]] || [[ "$requirement" =~ "<" ]] || [[ "$requirement" =~ ">" ]]; then
+                echo -e "\t- $requirement"
+              else
+                echo "::error::The requirement '$requirement' in '$component' is not pinned to a version or a range"
+                exit 1
+              fi
+            done
+
+            echo "${manifest}" | jq -e --raw-output '.requirements[]' >> requirements.txt
           done
 
       - name: Check if requirements.txt has content
