Check for json in filename (#294)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -31,6 +31,10 @@ jobs:
         run: |
           for component in components/*; do
             if [[ "${{ steps.changed_files.outputs.all }}" =~ $component ]]; then
+              if [ "${component##*.}" != "json" ];then
+                  echo "::error::${component} does not end with '.json'"
+                  exit 1
+              fi
               manifestlink=$(jq --raw-output ".manifest" "${component}")
 
               echo "Process: ${component} -> ${manifestlink}"
