Github Actions > Azure pipelines

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -12,7 +12,46 @@ env:
   DEFAULT_PYTHON: 3.8
 
 jobs:
+  lint:
+    runs-on: ubuntu-latest
+    name: Lint
+    outputs:
+      requirements: ${{ steps.requirements.outputs.exist }}
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+
+      - name: Lint with JQ
+        uses: home-assistant/actions/helpers/jq@master
+
+      - name: Check integration files
+        id: integrations
+        run: |
+          for component in components/*; do
+            manifestlink=$(jq --raw-output ".manifest" "${component}")
+
+            echo "Process: ${component} -> ${manifestlink}"
+            manifest=$(curl -sSL -f "${manifestlink}" | jq -e --raw-output .)
+            if [[ "$?" != 0 ]]; then
+              echo "Unable to read the manifest file at ${manifestlink}"
+              echo "The URL might be wrong or is not a raw URL."
+              exit 1
+            fi
+
+            echo "${manifest}" | jq -e --raw-output '.requirements[0]'
+            if [[ "$?" != 0 ]]; then
+              echo "The integration in $component, does not seem to have any Python requirements."
+              echo "Adding it to this repository has no use, since there are nothing to build for it."
+              exit 1
+            fi
+            
+            for requirement in $(echo "${manifest}" | jq -e --raw-output '.requirements[]'); do
+              echo -e "\t- $requirement"
+            done
+          done
+        
   requirements:
+    needs: lint
     runs-on: ubuntu-latest
     name: Validate Python requirements
     steps:
